# Generated by Django 4.2.20 on 2025-04-19 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True)),
                ('default_from_email', models.EmailField(default='noreply@example.com', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Setting',
                'verbose_name_plural': 'SMTP Settings',
            },
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='default_from_email',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='email_use_tls',
        ),
    ]
