# Generated by Django 4.2.20 on 2025-04-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_smtpsetting_remove_sitesetting_default_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='description',
            field=models.TextField(blank=True, help_text='About your site, used in footers and SEO.', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short slogan or tagline.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
