# Generated by Django 4.2.20 on 2025-04-20 08:06

from django.db import migrations, models
import django_quill.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting_description_sitesetting_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLegal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terms_of_service', django_quill.fields.QuillField()),
                ('privacy_policy', django_quill.fields.QuillField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
