# Generated by Django 4.2.20 on 2025-04-20 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_sitelegal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitelegal',
            options={'verbose_name_plural': 'Site Legal Content'},
        ),
        migrations.AddField(
            model_name='sitelegal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
